var movieTitle = "3 idiots";
movieTitle = "zindegi na milegi dubara";
// movieTitle=2000;
console.log(movieTitle.toUpperCase());
var NumOfLanguages = 3;
console.log("Number of languages known before year  2022", NumOfLanguages);
NumOfLanguages += 2;
console.log("Number of languages known in year 2022", NumOfLanguages);
var GameOver = true;
console.log("IS The Game Over?", GameOver);
GameOver = false;
console.log("IS The Game Over?", GameOver);
